package com.ScoreYourFood.demo.Enum;

public enum TipoComida {
    AREPAS,CAFETERIA,CALZONES,CARNES,CELIACOS,ARMENIA,CHINA,INDIA,JAPONESA,MEXICANA,PERUANA,VAGANA,VEGETERIANA,ÁRABE,CREPES,EMPANADAS,ENSALADAS,HAMBURGUESAS,HELADOS,LICUADOS,LOMITOS,MARISCOS,MILANESAS,PAPASFRITAS,PARRILLA,PASTAS,PESCADOS,PICADAS,PIZZAS,POLLO,POSTRES,SOPAS,SUSHI,SANDWICH,TARTAS,TORTILLAS,WOKS,WRAPS;
}
